prometheus:
  prometheusSpec:
    nodeSelector:
      kubernetes.io/hostname: nixos-3

    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:
  enabled: true
  nodeSelector:
    kubernetes.io/hostname: nixos-3
  persistence:
    enabled: true
    storageClassName: local-storage
    accessModes: ["ReadWriteOnce"]
    size: 5Gi

  defaultDashboardsEnabled: false

kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false

defaultRules:
  create: true

