apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
    - host: grafana.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vmks-grafana
                port:
                  number: 80

    - host: victoria-logs.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: victorialogs-victoria-logs-single-server
                port:
                  number: 9428
