apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: hello-pod-scrape
  labels:
    app: hello

spec:
  namespaceSelector:
    any: true

  selector:
    matchLabels:
      app: hello

  podMetricsEndpoints:
    - portNumber: 6666
      interval: 15s
