apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 1

  selector:
    matchLabels:
      app: hello

  template:
    metadata:
      labels:
        app: hello
    spec:
      terminationGracePeriodSeconds: 10

      containers:
        - name: hello
          image: ocir.ca-toronto-1.oci.oraclecloud.com/yzwl2hjkdzm1/hello:latest
          ports:
            - containerPort: 3000
              name: web
            - containerPort: 6666
              name: metrics

          env:
            - name: HTTP_PORT
              value: "3000"
            - name: DEVNULL_PORT
              value: "3001"
            - name: METRICS_PORT
              value: "6666"

            - name: VICTORIALOGS_HOST
              value: "victorialogs-victoria-logs-single-server.monitoring.svc.cluster.local"
            - name: VICTORIALOGS_PORT
              value: "9428"

            - name: OPENTELEMETRY_TRACE_HOST
              value: "tempo.monitoring.svc.cluster.local"
            - name: OPENTELEMETRY_TRACE_PORT
              value: "4318"

            - name: PYROSCOPE_HOST
              value: "pyroscope.monitoring.svc.cluster.local"
            - name: PYROSCOPE_PORT
              value: "4040"

            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

---
apiVersion: v1
kind: Service
metadata:
  name: hello-web
  namespace: default
  labels:
    app: hello
spec:
  selector:
    app: hello
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
