apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cluster-ips
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.10/32
  - 192.168.0.11/32
  - 192.168.0.12/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab-ips
  namespace: metallb-system
