repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

  - name: longhorn
    url: https://charts.longhorn.io

  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

  - name: metallb
    url: https://metallb.github.io/metallb

  - name: victoriametrics
    url: https://victoriametrics.github.io/helm-charts

releases:
  - name: kube-prometheus
    chart: prometheus-community/kube-prometheus-stack
    namespace: monitoring
    createNamespace: true
    values:
      - kube-prometheus-stack.yaml

  - name: longhorn
    chart: longhorn/longhorn
    namespace: longhorn-system
    createNamespace: true
    values:
      - longhorn.yaml

  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    values:
      - ingress-nginx.yaml

  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    createNamespace: true

  - name: victorialogs
    chart: victoriametrics/victoria-logs-single
    namespace: monitoring
    createNamespace: true
    values:
      - victorialogs.yaml

  - name: tempo
    chart: grafana/tempo
    namespace: monitoring
    createNamespace: true
    values:
      - tempo.yaml
