vmsingle:
  spec:
    retentionPeriod: "14d"
    storage:
      storageClassName: longhorn
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi

vmagent:
  spec:
    scrapeInterval: "15s"

defaultDashboards:
  enabled: true
  dashboards:
    node-exporter-full:
      enabled: true
    victoriametrics-operator:
      enabled: true
    victoriametrics-vmalert:
      enabled: true

grafana:
  enabled: true
  admin:
    existingSecret: vmks-grafana
    userKey: admin-user
    passwordKey: admin-password
  persistence:
    enabled: true
    storageClassName: longhorn
    accessModes: ["ReadWriteOnce"]
    size: 5Gi

kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false

defaultRules:
  create: true

